# Generated by Django 4.2.7 on 2023-11-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default='fsdsf', verbose_name='id чата'),
            preserve_default=False,
        ),
    ]
