# Generated by Django 4.2.7 on 2023-11-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='место')),
                ('hours', models.IntegerField(verbose_name='часы')),
                ('minutes', models.IntegerField(verbose_name='минуты')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.CharField(max_length=60, verbose_name='действие')),
                ('is_pleasant_habit', models.BooleanField(verbose_name='признак приятной привычки')),
                ('period', models.CharField(default='1D', max_length=30, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=30, null=True, verbose_name='вознаграждение')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
